package com.fitconnect.payment;

import com.fitconnect.payment.api.*; import com.fitconnect.payment.domain.*; import com.fitconnect.payment.repository.PaymentRepository; import com.fitconnect.payment.service.PaymentService; import org.junit.jupiter.api.*; import org.mockito.*; import java.math.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
class PaymentServiceTest { @Mock PaymentRepository repo; PaymentService service; @BeforeEach void init(){MockitoAnnotations.openMocks(this);service=new PaymentService(repo);}
 @Test void acceptsSmallAmountAndRefunds(){Payment p=new Payment(1L,"BK-1",2L,new BigDecimal("50"),PaymentMethod.CREDIT_CARD,"1234","txn");when(repo.save(any())).thenReturn(p);when(repo.findById(1L)).thenReturn(java.util.Optional.of(p));when(repo.findByBookingId(1L)).thenReturn(java.util.Optional.of(p));assertEquals(PaymentStatus.SUCCESS,service.pay(new PaymentRequest(1L,"BK-1",2L,new BigDecimal("50"),PaymentMethod.CREDIT_CARD,"1234","txn")).status());assertEquals(PaymentStatus.REFUNDED,service.refund(1L).status());assertNotNull(service.getByBooking(1L));}
 @Test void rejectsLargeAmountAndListsUser(){Payment p=new Payment(2L,"BK-2",2L,new BigDecimal("100"),PaymentMethod.PAYPAL,null,"txn");when(repo.save(any())).thenReturn(p);when(repo.findById(2L)).thenReturn(java.util.Optional.of(p));when(repo.findByUserId(2L)).thenReturn(java.util.List.of(p));assertEquals(PaymentStatus.FAILED,service.pay(new PaymentRequest(2L,"BK-2",2L,new BigDecimal("100"),PaymentMethod.PAYPAL,null,"txn")).status());assertEquals(1,service.byUser(2L).size());assertEquals(PaymentStatus.FAILED,service.refund(2L).status());}
 @Test void missingPaymentFails(){when(repo.findByBookingId(8L)).thenReturn(java.util.Optional.empty());when(repo.findById(8L)).thenReturn(java.util.Optional.empty());assertThrows(IllegalArgumentException.class,()->service.getByBooking(8L));assertThrows(IllegalArgumentException.class,()->service.refund(8L));}
 @Test void persistenceConstructorIsAvailable() throws Exception {var constructor=Payment.class.getDeclaredConstructor();constructor.setAccessible(true);assertNotNull(constructor.newInstance());}
}
