package com.fitconnect.classservice;

import com.fitconnect.classservice.api.*; import com.fitconnect.classservice.domain.*; import com.fitconnect.classservice.repository.FitnessClassRepository; import com.fitconnect.classservice.service.FitnessClassService; import org.junit.jupiter.api.*; import org.mockito.*; import org.springframework.data.domain.*; import java.math.*; import java.time.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;

class FitnessClassServiceTest {
    @Mock FitnessClassRepository repo; FitnessClassService service; FitnessClassRequest request;
    @BeforeEach void setUp(){MockitoAnnotations.openMocks(this);service=new FitnessClassService(repo);request=new FitnessClassRequest("Yoga","Desc","Marie","Paris",ClassCategory.YOGA,ClassLevel.BEGINNER,60,10,0,new BigDecimal("25"),LocalDateTime.now().plusDays(1));}
    @Test void createGetUpdateCancelIncrementDecrement(){FitnessClass c=new FitnessClass("Yoga","Desc","Marie","Paris",ClassCategory.YOGA,ClassLevel.BEGINNER,60,10,0,new BigDecimal("25"),request.dateTime());when(repo.save(any())).thenReturn(c);when(repo.findById(1L)).thenReturn(java.util.Optional.of(c));when(repo.saveAndFlush(any())).thenReturn(c);assertNotNull(service.create(request));FitnessClassRequest withoutCurrent=new FitnessClassRequest("Yoga","Desc","Marie","Paris",ClassCategory.YOGA,ClassLevel.BEGINNER,60,10,null,new BigDecimal("25"),request.dateTime());assertNotNull(service.create(withoutCurrent));assertNotNull(service.get(1L));assertNotNull(service.update(1L,request));assertNotNull(service.increment(1L,2));assertNotNull(service.decrement(1L,1));service.cancel(1L);verify(repo,atLeastOnce()).save(any());}
    @Test void searchAcceptsAllFilters(){when(repo.findAll(any(org.springframework.data.jpa.domain.Specification.class),any(Pageable.class))).thenReturn(Page.empty());assertTrue(service.search(ClassCategory.YOGA,ClassLevel.BEGINNER,LocalDateTime.now(),LocalDateTime.now().plusDays(1),"Paris","Marie",0,10,"dateTime,desc").isEmpty());assertTrue(service.search(null,null,null,null,null,null,0,10,"name,asc").isEmpty());assertTrue(service.search(null,null,null,null," ","",0,10,"name").isEmpty());}
    @Test void errorsAreRaised(){when(repo.findById(9L)).thenReturn(java.util.Optional.empty());assertThrows(IllegalArgumentException.class,()->service.get(9L));FitnessClassRequest invalid=new FitnessClassRequest("x","d","i","p",ClassCategory.YOGA,ClassLevel.BEGINNER,60,5,6,new BigDecimal("5"),request.dateTime());assertThrows(IllegalArgumentException.class,()->service.create(invalid));}
}
